experiments:
  - name: load_balancing
    resources:
      queue: hpcintro
      n_cores: 8
      walltime: "00:10"
      mem_per_core: "2GB"
      span: "hosts=1"
    sweep:
      n_ranks: [8]
      chunk_size: [50, 100, 250, 500, 750]
      image_shape:
        - {width: 10000, height: 10000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [0.0, 1.3]]
        - [[-2.2, 0.75], [-1.3, 1.3]]

  - name: scaling_proc
    resources:
      queue: hpcintro
      n_cores: 16
      walltime: "00:10"
      mem_per_core: "2GB"
      span: "hosts=1"
    sweep:
      n_ranks: [1, 4, 8, 10, 16, 20, 24]
      chunk_size: [8]
      image_shape:
        - {width: 10000, height: 10000}
        - {width: 20000, height: 20000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]


  - name: scaling_mult_host
    resources:
      queue: hpcintro
      n_cores: 100
      walltime: "00:25"
      mem_per_core: "4GB"
    sweep:
      n_ranks: [20, 30, 40, 50, 60, 70, 80, 90, 100]
      chunk_size: [50]
      image_shape:
        - {width: 20000, height: 20000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]

  - name: scaling_im
    resources:
      queue: hpcintro
      n_cores: 16
      walltime: "00:30"
      mem_per_core: "5GB"
      span: "hosts=1"
    sweep:
      n_ranks: [16]
      chunk_size: [50]
      image_shape:
        - {width: 1000, height: 1000}
        - {width: 5000, height: 5000}
        - {width: 10000, height: 10000}
        - {width: 20000, height: 20000}
        - {width: 30000, height: 30000}
        - {width: 40000, height: 40000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]
