experiments:
  - name: load_balancing
    resources:
      queue: hpcintro
      n_cores: 8
      walltime: "00:10"
      mem_per_core: "2GB"
      span: "hosts=1"
    sweep:
      n_ranks: [8]
      chunk_size: [50, 100, 250, 500, 750]
      image_shape:
        - {width: 10000, height: 10000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [0.0, 1.3]]
        - [[-2.2, 0.75], [-1.3, 1.3]]

  - name: scaling_proc
    resources:
      queue: hpcintro
      n_cores: 24
      walltime: "00:10"
      mem_per_core: "3GB"
      span: "hosts=1"
    sweep:
      n_ranks: [1, 4, 8, 10, 16, 20, 24]
      chunk_size: [100]
      image_shape:
        - {width: 20000, height: 20000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]


  - name: scaling_mult_host
    resources:
      queue: hpcintro
      n_cores: 70
      walltime: "00:10"
      mem_per_core: "5GB"
    sweep:
      n_ranks: [60, 70]
      chunk_size: [100]
      image_shape:
        - {width: 20000, height: 20000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]

  - name: scaling_im
    resources:
      queue: hpcintro
      n_cores: 16
      walltime: "00:15"
      mem_per_core: "5GB"
      span: "hosts=1"
    sweep:
      n_ranks: [16]
      chunk_size: [100]
      image_shape:
        - {width: 50000, height: 50000}
        - {width: 60000, height: 60000}
        - {width: 70000, height: 70000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]

  - name: TESTS
    resources:
      queue: local
      n_cores: 1
      walltime: "00:02"
      mem_per_core: "1GB"
    sweep:
      n_ranks: [1]
      chunk_size: [10]
      image_shape:
        - {width: 50, height: 50}
      schedule: [static]
      communication: [blocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]
