experiments:
  - name: TESTS
    resources:
      queue: hpcintro
      n_cores: 1
      walltime: "00:05"
      mem_per_core: "2GB"
      span: "hosts=1"
    sweep:
      n_ranks: [4,8]
      chunk_size: [10] 
      image_shape:
        - {width: 50, height: 50}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]

  - name: chunks
    resources:
      queue: hpcintro
      n_cores: 8
      walltime: "00:10"
      mem_per_core: "2GB"
      span: "hosts=1"
    sweep:
      n_ranks: [8]
      chunk_size: [4, 8, 16, 32, 64, 128, 256]
      image_shape:
        - {width: 5000, height: 5000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]

  - name: load_balancing
    resources:
      queue: hpcintro
      n_cores: 8
      walltime: "00:10"
      mem_per_core: "2GB"
      span: "hosts=1"
    sweep:
      n_ranks: [8]
      chunk_size: [8]
      image_shape:
        - {width: 5000, height: 5000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [0.0, 1.3]]
        - [[-2.2, 0.75], [-1.3, 1.3]]

  - name: scaling_proc
    resources:
      queue: hpcintro
      n_cores: 16
      walltime: "00:15"
      mem_per_core: "3GB"
      span: "hosts=1"
    sweep:
      n_ranks: [1, 4, 8, 16]
      chunk_size: [8]
      image_shape:
        - {width: 5000, height: 5000}
        - {width: 10000, height: 10000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]

  - name: scaling_im
    resources:
      queue: hpcintro
      n_cores: 16
      walltime: "00:30"
      mem_per_core: "3GB"
      span: "hosts=1"
    sweep:
      n_ranks: [16]
      chunk_size: [8]
      image_shape:
        - {width: 250, height: 250}
        - {width: 500, height: 500}
        - {width: 1000, height: 1000}
        - {width: 5000, height: 5000}
        - {width: 10000, height: 10000}
        - {width: 20000, height: 20000}
      schedule: [static, dynamic]
      communication: [blocking, nonblocking]
      domains:
        - [[-2.2, 0.75], [-1.3, 1.3]]
